# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'J:\our-py-lib\pepper\src\user_interface\/win_main.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(754, 507)
        MainWindow.setDockNestingEnabled(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setSpacing(3)
        self.gridLayout_3.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setFrameShape(QtWidgets.QFrame.Panel)
        self.graphicsView.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.graphicsView.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_3.addWidget(self.graphicsView, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 754, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dckProperties = QtWidgets.QDockWidget(MainWindow)
        self.dckProperties.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dckProperties.setObjectName("dckProperties")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnPropRest = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.btnPropRest.setObjectName("btnPropRest")
        self.gridLayout_2.addWidget(self.btnPropRest, 1, 4, 1, 1)
        self.btnPropApply = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.btnPropApply.setObjectName("btnPropApply")
        self.gridLayout_2.addWidget(self.btnPropApply, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 5, 1, 1)
        self.trProperties = QtWidgets.QTreeWidget(self.dockWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.trProperties.setFont(font)
        self.trProperties.setFrameShape(QtWidgets.QFrame.Panel)
        self.trProperties.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.trProperties.setDragEnabled(True)
        self.trProperties.setAlternatingRowColors(True)
        self.trProperties.setUniformRowHeights(True)
        self.trProperties.setAnimated(True)
        self.trProperties.setHeaderHidden(True)
        self.trProperties.setObjectName("trProperties")
        self.trProperties.headerItem().setText(0, "1")
        self.gridLayout_2.addWidget(self.trProperties, 0, 1, 1, 5)
        self.dckProperties.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dckProperties)
        self.dckNodes = QtWidgets.QDockWidget(MainWindow)
        self.dckNodes.setObjectName("dckNodes")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_4.setSpacing(2)
        self.gridLayout_4.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.trNodes = QtWidgets.QTreeWidget(self.dockWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.trNodes.setFont(font)
        self.trNodes.setFrameShape(QtWidgets.QFrame.Panel)
        self.trNodes.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.trNodes.setDragEnabled(True)
        self.trNodes.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.trNodes.setAlternatingRowColors(True)
        self.trNodes.setUniformRowHeights(True)
        self.trNodes.setAnimated(True)
        self.trNodes.setHeaderHidden(True)
        self.trNodes.setObjectName("trNodes")
        self.trNodes.headerItem().setText(0, "1")
        self.gridLayout_4.addWidget(self.trNodes, 0, 0, 1, 2)
        self.dckNodes.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dckNodes)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew_Scene = QtWidgets.QAction(MainWindow)
        self.actionNew_Scene.setObjectName("actionNew_Scene")
        self.actionLoad_Scene = QtWidgets.QAction(MainWindow)
        self.actionLoad_Scene.setObjectName("actionLoad_Scene")
        self.actionSave_Scene = QtWidgets.QAction(MainWindow)
        self.actionSave_Scene.setObjectName("actionSave_Scene")
        self.actionExecute = QtWidgets.QAction(MainWindow)
        self.actionExecute.setObjectName("actionExecute")
        self.actionProperties = QtWidgets.QAction(MainWindow)
        self.actionProperties.setCheckable(True)
        self.actionProperties.setObjectName("actionProperties")
        self.actionNodes = QtWidgets.QAction(MainWindow)
        self.actionNodes.setCheckable(True)
        self.actionNodes.setObjectName("actionNodes")
        self.toolBar.addAction(self.actionNew_Scene)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionLoad_Scene)
        self.toolBar.addAction(self.actionSave_Scene)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionNodes)
        self.toolBar.addAction(self.actionProperties)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExecute)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.dckProperties.visibilityChanged['bool'].connect(self.actionProperties.setChecked)
        self.actionProperties.toggled['bool'].connect(self.dckProperties.setVisible)
        self.dckNodes.visibilityChanged['bool'].connect(self.actionNodes.setChecked)
        self.actionNodes.toggled['bool'].connect(self.dckNodes.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pepper"))
        self.dckProperties.setWindowTitle(_translate("MainWindow", "Properties"))
        self.btnPropRest.setText(_translate("MainWindow", "Reset"))
        self.btnPropApply.setText(_translate("MainWindow", "Apply"))
        self.dckNodes.setWindowTitle(_translate("MainWindow", "Nodes"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNew_Scene.setText(_translate("MainWindow", "New Scene"))
        self.actionLoad_Scene.setText(_translate("MainWindow", "Load Scene"))
        self.actionSave_Scene.setText(_translate("MainWindow", "Save Scene"))
        self.actionExecute.setText(_translate("MainWindow", "Execute"))
        self.actionProperties.setText(_translate("MainWindow", "Properties"))
        self.actionNodes.setText(_translate("MainWindow", "Nodes"))

