# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'J:\our-py-lib\pepper\src\user_interface\/win_main.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(754, 507)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setFrameShape(QtWidgets.QFrame.Panel)
        self.splitter.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setOpaqueResize(False)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.graphicsView = QtWidgets.QGraphicsView(self.splitter)
        self.graphicsView.setFrameShape(QtWidgets.QFrame.Panel)
        self.graphicsView.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.graphicsView.setObjectName("graphicsView")
        self.textBrowser = QtWidgets.QTextBrowser(self.splitter)
        self.textBrowser.setFrameShape(QtWidgets.QFrame.Panel)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 754, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dckProperties = QtWidgets.QDockWidget(MainWindow)
        self.dckProperties.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dckProperties.setObjectName("dckProperties")
        self.df = QtWidgets.QWidget()
        self.df.setObjectName("df")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.df)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.df)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.tabWidget.setObjectName("tabWidget")
        self.tabDescription = QtWidgets.QWidget()
        self.tabDescription.setObjectName("tabDescription")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabDescription)
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.txtDescription = QtWidgets.QTextEdit(self.tabDescription)
        self.txtDescription.setReadOnly(True)
        self.txtDescription.setObjectName("txtDescription")
        self.gridLayout_3.addWidget(self.txtDescription, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabDescription, "")
        self.tabInputs = QtWidgets.QWidget()
        self.tabInputs.setObjectName("tabInputs")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tabInputs)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.splitter_3 = QtWidgets.QSplitter(self.tabInputs)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.trInput = QtWidgets.QTreeWidget(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.trInput.setFont(font)
        self.trInput.setFrameShape(QtWidgets.QFrame.Panel)
        self.trInput.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.trInput.setAlternatingRowColors(True)
        self.trInput.setUniformRowHeights(True)
        self.trInput.setAnimated(True)
        self.trInput.setHeaderHidden(True)
        self.trInput.setObjectName("trInput")
        self.trInput.headerItem().setText(0, "Inputs")
        self.trInput.header().setVisible(False)
        self.trOutput = QtWidgets.QTreeWidget(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.trOutput.setFont(font)
        self.trOutput.setFrameShape(QtWidgets.QFrame.Panel)
        self.trOutput.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.trOutput.setAlternatingRowColors(True)
        self.trOutput.setUniformRowHeights(True)
        self.trOutput.setAnimated(True)
        self.trOutput.setHeaderHidden(True)
        self.trOutput.setObjectName("trOutput")
        self.trOutput.headerItem().setText(0, "Available Outputs")
        self.trOutput.header().setVisible(False)
        self.groupBox = QtWidgets.QGroupBox(self.splitter_3)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.btnApplyInputs = QtWidgets.QPushButton(self.groupBox)
        self.btnApplyInputs.setObjectName("btnApplyInputs")
        self.gridLayout_5.addWidget(self.btnApplyInputs, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 1, 0, 1, 1)
        self.txtInputOutput = QtWidgets.QTextEdit(self.groupBox)
        self.txtInputOutput.setObjectName("txtInputOutput")
        self.gridLayout_5.addWidget(self.txtInputOutput, 0, 0, 1, 2)
        self.gridLayout_6.addWidget(self.splitter_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabInputs, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.dckProperties.setWidget(self.df)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dckProperties)
        self.dckNodes = QtWidgets.QDockWidget(MainWindow)
        self.dckNodes.setObjectName("dckNodes")
        self.dg = QtWidgets.QWidget()
        self.dg.setObjectName("dg")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.dg)
        self.gridLayout_4.setSpacing(2)
        self.gridLayout_4.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.trNodes = QtWidgets.QTreeWidget(self.dg)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.trNodes.setFont(font)
        self.trNodes.setFrameShape(QtWidgets.QFrame.Panel)
        self.trNodes.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.trNodes.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.trNodes.setAlternatingRowColors(True)
        self.trNodes.setUniformRowHeights(True)
        self.trNodes.setAnimated(True)
        self.trNodes.setHeaderHidden(True)
        self.trNodes.setObjectName("trNodes")
        self.trNodes.headerItem().setText(0, "1")
        self.gridLayout_4.addWidget(self.trNodes, 0, 0, 1, 2)
        self.dckNodes.setWidget(self.dg)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dckNodes)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew_Scene = QtWidgets.QAction(MainWindow)
        self.actionNew_Scene.setObjectName("actionNew_Scene")
        self.actionLoad_Scene = QtWidgets.QAction(MainWindow)
        self.actionLoad_Scene.setObjectName("actionLoad_Scene")
        self.actionSave_Scene = QtWidgets.QAction(MainWindow)
        self.actionSave_Scene.setObjectName("actionSave_Scene")
        self.actionExecute = QtWidgets.QAction(MainWindow)
        self.actionExecute.setObjectName("actionExecute")
        self.actionProperties = QtWidgets.QAction(MainWindow)
        self.actionProperties.setCheckable(True)
        self.actionProperties.setObjectName("actionProperties")
        self.actionNodes = QtWidgets.QAction(MainWindow)
        self.actionNodes.setCheckable(True)
        self.actionNodes.setObjectName("actionNodes")
        self.toolBar.addAction(self.actionNew_Scene)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionLoad_Scene)
        self.toolBar.addAction(self.actionSave_Scene)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionNodes)
        self.toolBar.addAction(self.actionProperties)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExecute)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.actionNodes.toggled['bool'].connect(self.dckNodes.setVisible)
        self.dckNodes.visibilityChanged['bool'].connect(self.actionNodes.setChecked)
        self.actionProperties.toggled['bool'].connect(self.dckProperties.setVisible)
        self.dckProperties.visibilityChanged['bool'].connect(self.actionProperties.setChecked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pepper"))
        self.dckProperties.setWindowTitle(_translate("MainWindow", "Properties"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDescription), _translate("MainWindow", "Description"))
        self.btnApplyInputs.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInputs), _translate("MainWindow", "Input-Output"))
        self.dckNodes.setWindowTitle(_translate("MainWindow", "Nodes"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNew_Scene.setText(_translate("MainWindow", "New Scene"))
        self.actionLoad_Scene.setText(_translate("MainWindow", "Load Scene"))
        self.actionSave_Scene.setText(_translate("MainWindow", "Save Scene"))
        self.actionExecute.setText(_translate("MainWindow", "Execute"))
        self.actionProperties.setText(_translate("MainWindow", "Properties"))
        self.actionNodes.setText(_translate("MainWindow", "Nodes"))

