# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Kumaresan\Code\Python\CommonLib\src\kmxPyQt\devConsole3\DCwin.ui'
#
# Created: Sun Oct 26 07:27:08 2014
#      by: PyQt5 UI code generator 5.3.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_devConsole(object):
    def setupUi(self, devConsole):
        devConsole.setObjectName("devConsole")
        devConsole.resize(689, 504)
        self.gridLayout_3 = QtWidgets.QGridLayout(devConsole)
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btnLoadScript = QtWidgets.QToolButton(devConsole)
        self.btnLoadScript.setMinimumSize(QtCore.QSize(75, 0))
        self.btnLoadScript.setMaximumSize(QtCore.QSize(75, 16777215))
        self.btnLoadScript.setAutoRaise(True)
        self.btnLoadScript.setObjectName("btnLoadScript")
        self.gridLayout_3.addWidget(self.btnLoadScript, 0, 2, 1, 1)
        self.btnSaveScript = QtWidgets.QToolButton(devConsole)
        self.btnSaveScript.setMinimumSize(QtCore.QSize(75, 0))
        self.btnSaveScript.setMaximumSize(QtCore.QSize(75, 16777215))
        self.btnSaveScript.setAutoRaise(True)
        self.btnSaveScript.setObjectName("btnSaveScript")
        self.gridLayout_3.addWidget(self.btnSaveScript, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(33, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 8, 1, 1)
        self.line = QtWidgets.QFrame(devConsole)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 0, 6, 1, 1)
        self.splitter = QtWidgets.QSplitter(devConsole)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setOpaqueResize(False)
        self.splitter.setObjectName("splitter")
        self.widget_2 = QtWidgets.QWidget(self.splitter)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 3, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.widget_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 1, 2, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.widget_2)
        self.toolButton.setCheckable(True)
        self.toolButton.setChecked(True)
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton.setAutoRaise(True)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_2.addWidget(self.toolButton, 1, 5, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.widget_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 1, 4, 1, 1)
        self.splitter_2 = QtWidgets.QSplitter(self.widget_2)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setOpaqueResize(False)
        self.splitter_2.setObjectName("splitter_2")
        self.sciOutput = QsciScintilla(self.splitter_2)
        self.sciOutput.setToolTip("")
        self.sciOutput.setWhatsThis("")
        self.sciOutput.setFrameShape(QtWidgets.QFrame.Box)
        self.sciOutput.setObjectName("sciOutput")
        self.treeWidget = QtWidgets.QTreeWidget(self.splitter_2)
        self.treeWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.treeWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setRootIsDecorated(True)
        self.treeWidget.setUniformRowHeights(True)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.treeWidget.header().setVisible(True)
        self.gridLayout_2.addWidget(self.splitter_2, 0, 0, 1, 6)
        self.btnClearOutput = QtWidgets.QToolButton(self.widget_2)
        self.btnClearOutput.setMinimumSize(QtCore.QSize(75, 0))
        self.btnClearOutput.setMaximumSize(QtCore.QSize(75, 16777215))
        self.btnClearOutput.setAutoRaise(True)
        self.btnClearOutput.setObjectName("btnClearOutput")
        self.gridLayout_2.addWidget(self.btnClearOutput, 1, 1, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.widget_2)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_2.addWidget(self.line_7, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setContentsMargins(2, -1, 2, 2)
        self.gridLayout.setObjectName("gridLayout")
        self.sciInput = QsciScintilla(self.widget)
        self.sciInput.setToolTip("")
        self.sciInput.setWhatsThis("")
        self.sciInput.setFrameShape(QtWidgets.QFrame.Box)
        self.sciInput.setObjectName("sciInput")
        self.gridLayout.addWidget(self.sciInput, 0, 0, 1, 7)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 5, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 0, 1, 1)
        self.btnExecute = QtWidgets.QToolButton(self.widget)
        self.btnExecute.setMinimumSize(QtCore.QSize(75, 0))
        self.btnExecute.setMaximumSize(QtCore.QSize(75, 16777215))
        self.btnExecute.setAutoRaise(True)
        self.btnExecute.setObjectName("btnExecute")
        self.gridLayout.addWidget(self.btnExecute, 1, 3, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.widget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 1, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.widget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 4, 1, 1)
        self.btnClearInput = QtWidgets.QToolButton(self.widget)
        self.btnClearInput.setMinimumSize(QtCore.QSize(75, 0))
        self.btnClearInput.setMaximumSize(QtCore.QSize(75, 16777215))
        self.btnClearInput.setAutoRaise(True)
        self.btnClearInput.setObjectName("btnClearInput")
        self.gridLayout.addWidget(self.btnClearInput, 1, 1, 1, 1)
        self.cline = QtWidgets.QLineEdit(self.splitter)
        self.cline.setMaximumSize(QtCore.QSize(16777215, 25))
        self.cline.setObjectName("cline")
        self.gridLayout_3.addWidget(self.splitter, 1, 0, 1, 9)

        self.retranslateUi(devConsole)
        QtCore.QMetaObject.connectSlotsByName(devConsole)

    def retranslateUi(self, devConsole):
        _translate = QtCore.QCoreApplication.translate
        devConsole.setWindowTitle(_translate("devConsole", "DevConsole"))
        self.btnLoadScript.setText(_translate("devConsole", "Load Script"))
        self.btnSaveScript.setText(_translate("devConsole", "Save Script"))
        self.toolButton.setText(_translate("devConsole", "Plugins"))
        self.treeWidget.setSortingEnabled(True)
        self.btnClearOutput.setText(_translate("devConsole", "Clear Outputs"))
        self.btnExecute.setText(_translate("devConsole", "Execute"))
        self.btnExecute.setShortcut(_translate("devConsole", "Ctrl+Enter"))
        self.btnClearInput.setText(_translate("devConsole", "Clear Inputs"))

from PyQt5.Qsci import QsciScintilla
