# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\REPO\SOURCE\SCRIPTS\PYTHON\LightNPray\ui\winLightNPray\lnp_ui.ui'
#
# Created: Mon Nov 29 11:10:53 2010
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(713, 792)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_9 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_9.setMargin(1)
        self.gridLayout_9.setSpacing(1)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.stkMainPages = QtGui.QStackedWidget(self.centralwidget)
        self.stkMainPages.setFrameShape(QtGui.QFrame.NoFrame)
        self.stkMainPages.setObjectName("stkMainPages")
        self.pgRenderFiles = QtGui.QWidget()
        self.pgRenderFiles.setObjectName("pgRenderFiles")
        self.gridLayout_16 = QtGui.QGridLayout(self.pgRenderFiles)
        self.gridLayout_16.setMargin(1)
        self.gridLayout_16.setSpacing(1)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.frame_14 = QtGui.QFrame(self.pgRenderFiles)
        self.frame_14.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_19 = QtGui.QGridLayout(self.frame_14)
        self.gridLayout_19.setSpacing(0)
        self.gridLayout_19.setContentsMargins(0, 2, 0, 0)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.tabWidget = QtGui.QTabWidget(self.frame_14)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_22 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_22.setMargin(0)
        self.gridLayout_22.setSpacing(0)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.trWorkFiles = QtGui.QTreeWidget(self.tab_2)
        self.trWorkFiles.setDragDropOverwriteMode(True)
        self.trWorkFiles.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.trWorkFiles.setAlternatingRowColors(True)
        self.trWorkFiles.setRootIsDecorated(True)
        self.trWorkFiles.setHeaderHidden(True)
        self.trWorkFiles.setObjectName("trWorkFiles")
        self.gridLayout_22.addWidget(self.trWorkFiles, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_23 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_23.setMargin(1)
        self.gridLayout_23.setSpacing(1)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.trRenderFiles = QtGui.QTreeWidget(self.tab_3)
        self.trRenderFiles.setDragDropOverwriteMode(True)
        self.trRenderFiles.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.trRenderFiles.setAlternatingRowColors(True)
        self.trRenderFiles.setRootIsDecorated(True)
        self.trRenderFiles.setHeaderHidden(True)
        self.trRenderFiles.setObjectName("trRenderFiles")
        self.gridLayout_23.addWidget(self.trRenderFiles, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout_19.addWidget(self.tabWidget, 3, 0, 1, 1)
        self.gridLayout_16.addWidget(self.frame_14, 1, 0, 1, 1)
        self.frame_5 = QtGui.QFrame(self.pgRenderFiles)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_18 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_18.setMargin(0)
        self.gridLayout_18.setSpacing(0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_14 = QtGui.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_18.addWidget(self.label_14, 0, 0, 1, 1)
        self.btnRenderFilesRender = QtGui.QToolButton(self.frame_5)
        self.btnRenderFilesRender.setMinimumSize(QtCore.QSize(80, 25))
        self.btnRenderFilesRender.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnRenderFilesRender.setAutoRaise(True)
        self.btnRenderFilesRender.setObjectName("btnRenderFilesRender")
        self.gridLayout_18.addWidget(self.btnRenderFilesRender, 0, 1, 1, 1)
        self.gridLayout_16.addWidget(self.frame_5, 0, 0, 1, 1)
        self.stkMainPages.addWidget(self.pgRenderFiles)
        self.pgPassDefinition = QtGui.QWidget()
        self.pgPassDefinition.setObjectName("pgPassDefinition")
        self.gridLayout_7 = QtGui.QGridLayout(self.pgPassDefinition)
        self.gridLayout_7.setMargin(1)
        self.gridLayout_7.setSpacing(1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_6 = QtGui.QFrame(self.pgPassDefinition)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_8 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.splitter_3 = QtGui.QSplitter(self.frame_6)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.frame_2 = QtGui.QFrame(self.splitter_3)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_4.setMargin(1)
        self.gridLayout_4.setSpacing(1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lbl = QtGui.QLabel(self.frame_2)
        self.lbl.setObjectName("lbl")
        self.gridLayout_4.addWidget(self.lbl, 0, 0, 1, 1)
        self.btnPassTypeRemove = QtGui.QToolButton(self.frame_2)
        self.btnPassTypeRemove.setAutoRaise(True)
        self.btnPassTypeRemove.setObjectName("btnPassTypeRemove")
        self.gridLayout_4.addWidget(self.btnPassTypeRemove, 0, 1, 1, 1)
        self.btnPassTypeAdd = QtGui.QToolButton(self.frame_2)
        self.btnPassTypeAdd.setAutoRaise(True)
        self.btnPassTypeAdd.setObjectName("btnPassTypeAdd")
        self.gridLayout_4.addWidget(self.btnPassTypeAdd, 0, 2, 1, 1)
        self.trList_2 = QtGui.QTreeWidget(self.frame_2)
        self.trList_2.setAlternatingRowColors(True)
        self.trList_2.setRootIsDecorated(False)
        self.trList_2.setHeaderHidden(True)
        self.trList_2.setObjectName("trList_2")
        self.gridLayout_4.addWidget(self.trList_2, 1, 0, 1, 3)
        self.frame_4 = QtGui.QFrame(self.splitter_3)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_6 = QtGui.QGridLayout(self.frame_4)
        self.gridLayout_6.setMargin(1)
        self.gridLayout_6.setSpacing(1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_8 = QtGui.QLabel(self.frame_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 0, 0, 1, 1)
        self.btnPassRemove = QtGui.QToolButton(self.frame_4)
        self.btnPassRemove.setAutoRaise(True)
        self.btnPassRemove.setObjectName("btnPassRemove")
        self.gridLayout_6.addWidget(self.btnPassRemove, 0, 1, 1, 1)
        self.btnPassAdd = QtGui.QToolButton(self.frame_4)
        self.btnPassAdd.setAutoRaise(True)
        self.btnPassAdd.setObjectName("btnPassAdd")
        self.gridLayout_6.addWidget(self.btnPassAdd, 0, 2, 1, 1)
        self.trList_3 = QtGui.QTreeWidget(self.frame_4)
        self.trList_3.setAlternatingRowColors(True)
        self.trList_3.setRootIsDecorated(False)
        self.trList_3.setHeaderHidden(True)
        self.trList_3.setObjectName("trList_3")
        self.gridLayout_6.addWidget(self.trList_3, 1, 0, 1, 3)
        self.frame_3 = QtGui.QFrame(self.splitter_3)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_3.setMargin(1)
        self.gridLayout_3.setSpacing(1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lbl_2 = QtGui.QLabel(self.frame_3)
        self.lbl_2.setObjectName("lbl_2")
        self.gridLayout_3.addWidget(self.lbl_2, 0, 0, 1, 1)
        self.btnAOVRemove = QtGui.QToolButton(self.frame_3)
        self.btnAOVRemove.setAutoRaise(True)
        self.btnAOVRemove.setObjectName("btnAOVRemove")
        self.gridLayout_3.addWidget(self.btnAOVRemove, 0, 1, 1, 1)
        self.btnAOVAdd = QtGui.QToolButton(self.frame_3)
        self.btnAOVAdd.setAutoRaise(True)
        self.btnAOVAdd.setObjectName("btnAOVAdd")
        self.gridLayout_3.addWidget(self.btnAOVAdd, 0, 2, 1, 1)
        self.trList_4 = QtGui.QTreeWidget(self.frame_3)
        self.trList_4.setAlternatingRowColors(True)
        self.trList_4.setRootIsDecorated(False)
        self.trList_4.setHeaderHidden(True)
        self.trList_4.setObjectName("trList_4")
        self.gridLayout_3.addWidget(self.trList_4, 1, 0, 1, 3)
        self.gridLayout_8.addWidget(self.splitter_3, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_6, 4, 0, 1, 2)
        self.frame_12 = QtGui.QFrame(self.pgPassDefinition)
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_20 = QtGui.QGridLayout(self.frame_12)
        self.gridLayout_20.setMargin(0)
        self.gridLayout_20.setSpacing(0)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label = QtGui.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_20.addWidget(self.label, 0, 0, 1, 1)
        self.btnPassDefSave = QtGui.QToolButton(self.frame_12)
        self.btnPassDefSave.setMinimumSize(QtCore.QSize(80, 25))
        self.btnPassDefSave.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnPassDefSave.setAutoRaise(True)
        self.btnPassDefSave.setObjectName("btnPassDefSave")
        self.gridLayout_20.addWidget(self.btnPassDefSave, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.frame_12, 2, 0, 1, 2)
        self.stkMainPages.addWidget(self.pgPassDefinition)
        self.pgBuildPass = QtGui.QWidget()
        self.pgBuildPass.setObjectName("pgBuildPass")
        self.gridLayout_14 = QtGui.QGridLayout(self.pgBuildPass)
        self.gridLayout_14.setMargin(1)
        self.gridLayout_14.setSpacing(1)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.frame_7 = QtGui.QFrame(self.pgBuildPass)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_10 = QtGui.QGridLayout(self.frame_7)
        self.gridLayout_10.setMargin(1)
        self.gridLayout_10.setSpacing(1)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.splitter_2 = QtGui.QSplitter(self.frame_7)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.frame_9 = QtGui.QFrame(self.splitter_2)
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_12 = QtGui.QGridLayout(self.frame_9)
        self.gridLayout_12.setMargin(1)
        self.gridLayout_12.setSpacing(1)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_10 = QtGui.QLabel(self.frame_9)
        self.label_10.setObjectName("label_10")
        self.gridLayout_12.addWidget(self.label_10, 1, 0, 1, 1)
        self.trPg2List_2 = QtGui.QTreeWidget(self.frame_9)
        self.trPg2List_2.setDragEnabled(True)
        self.trPg2List_2.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.trPg2List_2.setAlternatingRowColors(True)
        self.trPg2List_2.setIndentation(10)
        self.trPg2List_2.setRootIsDecorated(True)
        self.trPg2List_2.setHeaderHidden(True)
        self.trPg2List_2.setObjectName("trPg2List_2")
        self.gridLayout_12.addWidget(self.trPg2List_2, 2, 0, 1, 2)
        self.frame_10 = QtGui.QFrame(self.splitter_2)
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_13 = QtGui.QGridLayout(self.frame_10)
        self.gridLayout_13.setMargin(1)
        self.gridLayout_13.setSpacing(1)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_11 = QtGui.QLabel(self.frame_10)
        self.label_11.setObjectName("label_11")
        self.gridLayout_13.addWidget(self.label_11, 0, 0, 1, 1)
        self.btnPassSceneRemove = QtGui.QToolButton(self.frame_10)
        self.btnPassSceneRemove.setAutoRaise(True)
        self.btnPassSceneRemove.setObjectName("btnPassSceneRemove")
        self.gridLayout_13.addWidget(self.btnPassSceneRemove, 0, 1, 1, 1)
        self.btnPassSceneAdd = QtGui.QToolButton(self.frame_10)
        self.btnPassSceneAdd.setAutoRaise(True)
        self.btnPassSceneAdd.setObjectName("btnPassSceneAdd")
        self.gridLayout_13.addWidget(self.btnPassSceneAdd, 0, 2, 1, 1)
        self.trPg2List = QtGui.QTreeWidget(self.frame_10)
        self.trPg2List.setDragDropOverwriteMode(True)
        self.trPg2List.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.trPg2List.setAlternatingRowColors(True)
        self.trPg2List.setIndentation(10)
        self.trPg2List.setRootIsDecorated(True)
        self.trPg2List.setUniformRowHeights(True)
        self.trPg2List.setHeaderHidden(False)
        self.trPg2List.setObjectName("trPg2List")
        self.gridLayout_13.addWidget(self.trPg2List, 1, 0, 1, 3)
        self.gridLayout_10.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.frame_7, 1, 0, 1, 1)
        self.frame = QtGui.QFrame(self.pgBuildPass)
        self.frame.setMinimumSize(QtCore.QSize(0, 30))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_17 = QtGui.QGridLayout(self.frame)
        self.gridLayout_17.setMargin(0)
        self.gridLayout_17.setSpacing(0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(0, 14))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_17.addWidget(self.label_2, 0, 0, 1, 1)
        self.btnBuildFilesBuild = QtGui.QToolButton(self.frame)
        self.btnBuildFilesBuild.setMinimumSize(QtCore.QSize(80, 25))
        self.btnBuildFilesBuild.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnBuildFilesBuild.setAutoRaise(True)
        self.btnBuildFilesBuild.setObjectName("btnBuildFilesBuild")
        self.gridLayout_17.addWidget(self.btnBuildFilesBuild, 0, 2, 1, 1)
        self.btnBuildFilesSave = QtGui.QToolButton(self.frame)
        self.btnBuildFilesSave.setMinimumSize(QtCore.QSize(80, 25))
        self.btnBuildFilesSave.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnBuildFilesSave.setAutoRaise(True)
        self.btnBuildFilesSave.setObjectName("btnBuildFilesSave")
        self.gridLayout_17.addWidget(self.btnBuildFilesSave, 0, 1, 1, 1)
        self.gridLayout_14.addWidget(self.frame, 0, 0, 1, 1)
        self.stkMainPages.addWidget(self.pgBuildPass)
        self.gridLayout_9.addWidget(self.stkMainPages, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 713, 21))
        self.menubar.setObjectName("menubar")
        self.menuCreate = QtGui.QMenu(self.menubar)
        self.menuCreate.setObjectName("menuCreate")
        self.menuGlobals = QtGui.QMenu(self.menubar)
        self.menuGlobals.setObjectName("menuGlobals")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuWindows = QtGui.QMenu(self.menubar)
        self.menuWindows.setObjectName("menuWindows")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dckSNS = QtGui.QDockWidget(MainWindow)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.dckSNS.setFont(font)
        self.dckSNS.setObjectName("dckSNS")
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout_5 = QtGui.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_5.setMargin(1)
        self.gridLayout_5.setSpacing(1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.splitter = QtGui.QSplitter(self.dockWidgetContents_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame_11 = QtGui.QFrame(self.splitter)
        self.frame_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_15 = QtGui.QGridLayout(self.frame_11)
        self.gridLayout_15.setMargin(1)
        self.gridLayout_15.setSpacing(1)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.trListSeq = QtGui.QTreeWidget(self.frame_11)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.trListSeq.setFont(font)
        self.trListSeq.setAlternatingRowColors(True)
        self.trListSeq.setRootIsDecorated(False)
        self.trListSeq.setObjectName("trListSeq")
        self.gridLayout_15.addWidget(self.trListSeq, 0, 0, 1, 1)
        self.frame_8 = QtGui.QFrame(self.splitter)
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_11 = QtGui.QGridLayout(self.frame_8)
        self.gridLayout_11.setMargin(1)
        self.gridLayout_11.setSpacing(1)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.trList = QtGui.QTreeWidget(self.frame_8)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.trList.setFont(font)
        self.trList.setAlternatingRowColors(True)
        self.trList.setRootIsDecorated(False)
        self.trList.setObjectName("trList")
        self.gridLayout_11.addWidget(self.trList, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.splitter, 0, 0, 1, 1)
        self.dckSNS.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dckSNS)
        self.dckRenderSettings = QtGui.QDockWidget(MainWindow)
        self.dckRenderSettings.setFloating(False)
        self.dckRenderSettings.setObjectName("dckRenderSettings")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setMargin(1)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget_9 = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget_9.setObjectName("tabWidget_9")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_21 = QtGui.QGridLayout(self.tab)
        self.gridLayout_21.setMargin(1)
        self.gridLayout_21.setHorizontalSpacing(1)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.scrollArea = QtGui.QScrollArea(self.tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 431, 396))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_24 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_24.setSpacing(2)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.groupBox_5 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayout_6 = QtGui.QFormLayout(self.groupBox_5)
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setContentsMargins(9, 9, -1, -1)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_15 = QtGui.QLabel(self.groupBox_5)
        self.label_15.setMinimumSize(QtCore.QSize(75, 0))
        self.label_15.setObjectName("label_15")
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_15)
        self.lineEdit = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit)
        self.label_16 = QtGui.QLabel(self.groupBox_5)
        self.label_16.setMinimumSize(QtCore.QSize(75, 0))
        self.label_16.setObjectName("label_16")
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_16)
        self.lineEdit_4 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_4)
        self.lineEdit_10 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_10)
        self.label_17 = QtGui.QLabel(self.groupBox_5)
        self.label_17.setMinimumSize(QtCore.QSize(75, 0))
        self.label_17.setObjectName("label_17")
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_17)
        self.lineEdit_11 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_11)
        self.label_18 = QtGui.QLabel(self.groupBox_5)
        self.label_18.setMinimumSize(QtCore.QSize(75, 0))
        self.label_18.setObjectName("label_18")
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_18)
        self.gridLayout_24.addWidget(self.groupBox_5, 2, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_4 = QtGui.QFormLayout(self.groupBox_4)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setMinimumSize(QtCore.QSize(75, 0))
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_12 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_12)
        self.lineEdit_13 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_13)
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_3.setObjectName("checkBox_3")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.checkBox_3)
        self.label_19 = QtGui.QLabel(self.groupBox_4)
        self.label_19.setMinimumSize(QtCore.QSize(75, 0))
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_19)
        self.gridLayout_24.addWidget(self.groupBox_4, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_24.addItem(spacerItem, 4, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_6.setObjectName("groupBox_6")
        self.formLayout_5 = QtGui.QFormLayout(self.groupBox_6)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_20 = QtGui.QLabel(self.groupBox_6)
        self.label_20.setMinimumSize(QtCore.QSize(75, 0))
        self.label_20.setObjectName("label_20")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_20)
        self.lineEdit_6 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_6)
        self.lineEdit_9 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_9)
        self.label_21 = QtGui.QLabel(self.groupBox_6)
        self.label_21.setMinimumSize(QtCore.QSize(75, 0))
        self.label_21.setObjectName("label_21")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_21)
        self.gridLayout_24.addWidget(self.groupBox_6, 3, 0, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_7.setObjectName("groupBox_7")
        self.formLayout_7 = QtGui.QFormLayout(self.groupBox_7)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_9 = QtGui.QLabel(self.groupBox_7)
        self.label_9.setMinimumSize(QtCore.QSize(75, 0))
        self.label_9.setObjectName("label_9")
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_14 = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_14)
        self.gridLayout_24.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_21.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget_9.addTab(self.tab, "")
        self.tab_15 = QtGui.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.gridLayout_26 = QtGui.QGridLayout(self.tab_15)
        self.gridLayout_26.setMargin(1)
        self.gridLayout_26.setHorizontalSpacing(1)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.scrollArea_2 = QtGui.QScrollArea(self.tab_15)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget(self.scrollArea_2)
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 214, 394))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_25 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_25.setSpacing(2)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setMinimumSize(QtCore.QSize(75, 0))
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.comboBox = QtGui.QComboBox(self.groupBox_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBox)
        self.gridLayout_25.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_3 = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_23 = QtGui.QLabel(self.groupBox_3)
        self.label_23.setMinimumSize(QtCore.QSize(75, 0))
        self.label_23.setObjectName("label_23")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_23)
        self.comboBox_2 = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_2.setObjectName("comboBox_2")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBox_2)
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_2.setObjectName("checkBox_2")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.checkBox_2)
        self.gridLayout_25.addWidget(self.groupBox_3, 7, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_25.addItem(spacerItem1, 9, 0, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_8.setObjectName("groupBox_8")
        self.formLayout_8 = QtGui.QFormLayout(self.groupBox_8)
        self.formLayout_8.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_8.setContentsMargins(9, 9, -1, -1)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_24 = QtGui.QLabel(self.groupBox_8)
        self.label_24.setMinimumSize(QtCore.QSize(75, 0))
        self.label_24.setObjectName("label_24")
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_24)
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_25 = QtGui.QLabel(self.groupBox_8)
        self.label_25.setMinimumSize(QtCore.QSize(75, 0))
        self.label_25.setObjectName("label_25")
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_25)
        self.lineEdit_15 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_15.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_15)
        self.gridLayout_25.addWidget(self.groupBox_8, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.checkBox = QtGui.QCheckBox(self.groupBox)
        self.checkBox.setObjectName("checkBox")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.checkBox)
        self.spinBox_3 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBox_3.setObjectName("spinBox_3")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinBox_3)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setMinimumSize(QtCore.QSize(75, 0))
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.spinBox = QtGui.QSpinBox(self.groupBox)
        self.spinBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBox.setObjectName("spinBox")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.spinBox)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.spinBox_2 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.spinBox_2)
        self.label_22 = QtGui.QLabel(self.groupBox)
        self.label_22.setObjectName("label_22")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_22)
        self.gridLayout_25.addWidget(self.groupBox, 6, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_26.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.tabWidget_9.addTab(self.tab_15, "")
        self.tab_16 = QtGui.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.gridLayout_28 = QtGui.QGridLayout(self.tab_16)
        self.gridLayout_28.setMargin(1)
        self.gridLayout_28.setHorizontalSpacing(1)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.scrollArea_3 = QtGui.QScrollArea(self.tab_16)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtGui.QWidget(self.scrollArea_3)
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 157, 154))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_27 = QtGui.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_27.setSpacing(2)
        self.gridLayout_27.setObjectName("gridLayout_27")
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_27.addItem(spacerItem2, 3, 0, 1, 1)
        self.groupBox_13 = QtGui.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_13.setObjectName("groupBox_13")
        self.formLayout_13 = QtGui.QFormLayout(self.groupBox_13)
        self.formLayout_13.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_13.setObjectName("formLayout_13")
        self.label_27 = QtGui.QLabel(self.groupBox_13)
        self.label_27.setObjectName("label_27")
        self.formLayout_13.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_27)
        self.comboBox_3 = QtGui.QComboBox(self.groupBox_13)
        self.comboBox_3.setObjectName("comboBox_3")
        self.formLayout_13.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBox_3)
        self.gridLayout_27.addWidget(self.groupBox_13, 0, 0, 1, 1)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.scrollAreaWidgetContents_3)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 120))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_27.addWidget(self.plainTextEdit, 2, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_26.setObjectName("label_26")
        self.gridLayout_27.addWidget(self.label_26, 1, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_28.addWidget(self.scrollArea_3, 0, 0, 1, 1)
        self.tabWidget_9.addTab(self.tab_16, "")
        self.gridLayout.addWidget(self.tabWidget_9, 0, 0, 1, 1)
        self.dckRenderSettings.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dckRenderSettings)
        self.dckLog = QtGui.QDockWidget(MainWindow)
        self.dckLog.setObjectName("dckLog")
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_2.setMargin(1)
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tbLog = QtGui.QTextBrowser(self.dockWidgetContents_3)
        self.tbLog.setObjectName("tbLog")
        self.gridLayout_2.addWidget(self.tbLog, 0, 0, 1, 1)
        self.dckLog.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dckLog)
        self.toolBar_2 = QtGui.QToolBar(MainWindow)
        self.toolBar_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionPass_Definition = QtGui.QAction(MainWindow)
        self.actionPass_Definition.setCheckable(True)
        self.actionPass_Definition.setObjectName("actionPass_Definition")
        self.actionBuild_Files = QtGui.QAction(MainWindow)
        self.actionBuild_Files.setCheckable(True)
        self.actionBuild_Files.setObjectName("actionBuild_Files")
        self.actionRender_Files = QtGui.QAction(MainWindow)
        self.actionRender_Files.setCheckable(True)
        self.actionRender_Files.setObjectName("actionRender_Files")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionLogs = QtGui.QAction(MainWindow)
        self.actionLogs.setCheckable(True)
        self.actionLogs.setChecked(True)
        self.actionLogs.setObjectName("actionLogs")
        self.actionRender_Settings = QtGui.QAction(MainWindow)
        self.actionRender_Settings.setCheckable(True)
        self.actionRender_Settings.setChecked(True)
        self.actionRender_Settings.setObjectName("actionRender_Settings")
        self.actionSeq_N_Shots = QtGui.QAction(MainWindow)
        self.actionSeq_N_Shots.setCheckable(True)
        self.actionSeq_N_Shots.setChecked(True)
        self.actionSeq_N_Shots.setObjectName("actionSeq_N_Shots")
        self.menuCreate.addAction(self.actionSave)
        self.menuCreate.addSeparator()
        self.menuCreate.addAction(self.actionQuit)
        self.menuGlobals.addAction(self.actionPass_Definition)
        self.menuGlobals.addAction(self.actionBuild_Files)
        self.menuGlobals.addAction(self.actionRender_Files)
        self.menuWindows.addAction(self.actionSeq_N_Shots)
        self.menuWindows.addAction(self.actionRender_Settings)
        self.menuWindows.addSeparator()
        self.menuWindows.addAction(self.actionLogs)
        self.menubar.addAction(self.menuCreate.menuAction())
        self.menubar.addAction(self.menuGlobals.menuAction())
        self.menubar.addAction(self.menuWindows.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar_2.addAction(self.actionPass_Definition)
        self.toolBar_2.addAction(self.actionBuild_Files)
        self.toolBar_2.addAction(self.actionRender_Files)

        self.retranslateUi(MainWindow)
        self.stkMainPages.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_9.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.trWorkFiles.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Pass Type", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Work Files", None, QtGui.QApplication.UnicodeUTF8))
        self.trRenderFiles.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Pass Type", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Render Files", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Render Files", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRenderFilesRender.setText(QtGui.QApplication.translate("MainWindow", "Render", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl.setText(QtGui.QApplication.translate("MainWindow", "Pass Type", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPassTypeRemove.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPassTypeAdd.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.trList_2.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Pass Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Passes", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPassRemove.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPassAdd.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.trList_3.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Pass Type", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_2.setText(QtGui.QApplication.translate("MainWindow", "AOV", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAOVRemove.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAOVAdd.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.trList_4.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Pass Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Pass Definition", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPassDefSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Assets", None, QtGui.QApplication.UnicodeUTF8))
        self.trPg2List_2.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Pass Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Pass Scenes", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPassSceneRemove.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPassSceneAdd.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.trPg2List.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Scene Name", None, QtGui.QApplication.UnicodeUTF8))
        self.trPg2List.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Pass Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Build Files", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBuildFilesBuild.setText(QtGui.QApplication.translate("MainWindow", "Build", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBuildFilesSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCreate.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuGlobals.setTitle(QtGui.QApplication.translate("MainWindow", "Pass Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWindows.setTitle(QtGui.QApplication.translate("MainWindow", "Window", None, QtGui.QApplication.UnicodeUTF8))
        self.dckSNS.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Sequences and Shots", None, QtGui.QApplication.UnicodeUTF8))
        self.trListSeq.setSortingEnabled(True)
        self.trListSeq.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Sequences", None, QtGui.QApplication.UnicodeUTF8))
        self.trList.setSortingEnabled(True)
        self.trList.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Shots", None, QtGui.QApplication.UnicodeUTF8))
        self.dckRenderSettings.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Render Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Image", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Height", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Image Format", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Image Depth", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Render", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Renderer", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_12.setText(QtGui.QApplication.translate("MainWindow", "Mayaman", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_13.setText(QtGui.QApplication.translate("MainWindow", "Air", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("MainWindow", "Stereo Render", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Render Engine", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Aspect Ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Device", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "Maya", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Version", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_9.setTabText(self.tabWidget_9.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Project Globals", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Work File", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Render As", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "ScnImg", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "ScnRibImg", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "RibOnly", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "RibImg", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("MainWindow", "Stereo Render", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("MainWindow", "Image", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Height", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Frames", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("MainWindow", "Frame Range", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Frames", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Start Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "End Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_9.setTabText(self.tabWidget_9.indexOf(self.tab_15), QtGui.QApplication.translate("MainWindow", "Scene Globals", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_13.setTitle(QtGui.QApplication.translate("MainWindow", "Mayaman Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Bit Depth", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_9.setTabText(self.tabWidget_9.indexOf(self.tab_16), QtGui.QApplication.translate("MainWindow", "Pass Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.dckLog.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.tbLog.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_2.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar_2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPass_Definition.setText(QtGui.QApplication.translate("MainWindow", "Pass Definition", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBuild_Files.setText(QtGui.QApplication.translate("MainWindow", "Build Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRender_Files.setText(QtGui.QApplication.translate("MainWindow", "Render Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLogs.setText(QtGui.QApplication.translate("MainWindow", "Logs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRender_Settings.setText(QtGui.QApplication.translate("MainWindow", "Render Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSeq_N_Shots.setText(QtGui.QApplication.translate("MainWindow", "Seq N Shots", None, QtGui.QApplication.UnicodeUTF8))

