# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Kumaresan\Code\Python\CommonLib\src\kmxPyQt\devConsole3\DCwin.ui'
#
# Created: Wed Oct 15 23:11:52 2014
#      by: PyQt5 UI code generator 5.3.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_devConsole(object):
    def setupUi(self, devConsole):
        devConsole.setObjectName("devConsole")
        devConsole.resize(689, 504)
        self.gridLayout_3 = QtWidgets.QGridLayout(devConsole)
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btnClearInput = QtWidgets.QToolButton(devConsole)
        self.btnClearInput.setMinimumSize(QtCore.QSize(75, 0))
        self.btnClearInput.setMaximumSize(QtCore.QSize(75, 16777215))
        self.btnClearInput.setAutoRaise(True)
        self.btnClearInput.setObjectName("btnClearInput")
        self.gridLayout_3.addWidget(self.btnClearInput, 0, 0, 1, 1)
        self.btnClearOutput = QtWidgets.QToolButton(devConsole)
        self.btnClearOutput.setMinimumSize(QtCore.QSize(75, 0))
        self.btnClearOutput.setMaximumSize(QtCore.QSize(75, 16777215))
        self.btnClearOutput.setAutoRaise(True)
        self.btnClearOutput.setObjectName("btnClearOutput")
        self.gridLayout_3.addWidget(self.btnClearOutput, 0, 1, 1, 1)
        self.btnLoadScript = QtWidgets.QToolButton(devConsole)
        self.btnLoadScript.setMinimumSize(QtCore.QSize(75, 0))
        self.btnLoadScript.setMaximumSize(QtCore.QSize(75, 16777215))
        self.btnLoadScript.setAutoRaise(True)
        self.btnLoadScript.setObjectName("btnLoadScript")
        self.gridLayout_3.addWidget(self.btnLoadScript, 0, 2, 1, 1)
        self.btnSaveScript = QtWidgets.QToolButton(devConsole)
        self.btnSaveScript.setMinimumSize(QtCore.QSize(75, 0))
        self.btnSaveScript.setMaximumSize(QtCore.QSize(75, 16777215))
        self.btnSaveScript.setAutoRaise(True)
        self.btnSaveScript.setObjectName("btnSaveScript")
        self.gridLayout_3.addWidget(self.btnSaveScript, 0, 3, 1, 1)
        self.btnExecute = QtWidgets.QToolButton(devConsole)
        self.btnExecute.setMinimumSize(QtCore.QSize(75, 0))
        self.btnExecute.setMaximumSize(QtCore.QSize(75, 16777215))
        self.btnExecute.setAutoRaise(True)
        self.btnExecute.setObjectName("btnExecute")
        self.gridLayout_3.addWidget(self.btnExecute, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(33, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 7, 1, 1)
        self.line = QtWidgets.QFrame(devConsole)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 0, 5, 1, 1)
        self.splitter = QtWidgets.QSplitter(devConsole)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.widget_2 = QtWidgets.QWidget(self.splitter)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter_2 = QtWidgets.QSplitter(self.widget_2)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.sciOutput = QsciScintilla(self.splitter_2)
        self.sciOutput.setToolTip("")
        self.sciOutput.setWhatsThis("")
        self.sciOutput.setFrameShape(QtWidgets.QFrame.Box)
        self.sciOutput.setObjectName("sciOutput")
        self.treeWidget = QtWidgets.QTreeWidget(self.splitter_2)
        self.treeWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.treeWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setIndentation(0)
        self.treeWidget.setRootIsDecorated(False)
        self.treeWidget.setUniformRowHeights(True)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.treeWidget.header().setVisible(True)
        self.gridLayout_2.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setContentsMargins(2, -1, 2, 2)
        self.gridLayout.setObjectName("gridLayout")
        self.sciInput = QsciScintilla(self.widget)
        self.sciInput.setToolTip("")
        self.sciInput.setWhatsThis("")
        self.sciInput.setFrameShape(QtWidgets.QFrame.Box)
        self.sciInput.setObjectName("sciInput")
        self.gridLayout.addWidget(self.sciInput, 0, 0, 1, 1)
        self.cline = QtWidgets.QLineEdit(self.splitter)
        self.cline.setMaximumSize(QtCore.QSize(16777215, 25))
        self.cline.setObjectName("cline")
        self.gridLayout_3.addWidget(self.splitter, 1, 0, 1, 8)
        self.pushButton = QtWidgets.QPushButton(devConsole)
        self.pushButton.setCheckable(True)
        self.pushButton.setChecked(True)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 6, 1, 1)

        self.retranslateUi(devConsole)
        self.pushButton.clicked['bool'].connect(self.treeWidget.setVisible)
        QtCore.QMetaObject.connectSlotsByName(devConsole)

    def retranslateUi(self, devConsole):
        _translate = QtCore.QCoreApplication.translate
        devConsole.setWindowTitle(_translate("devConsole", "DevConsole"))
        self.btnClearInput.setText(_translate("devConsole", "Clear Inputs"))
        self.btnClearOutput.setText(_translate("devConsole", "Clear Outputs"))
        self.btnLoadScript.setText(_translate("devConsole", "Load Script"))
        self.btnSaveScript.setText(_translate("devConsole", "Save Script"))
        self.btnExecute.setText(_translate("devConsole", "Execute"))
        self.btnExecute.setShortcut(_translate("devConsole", "Ctrl+Enter"))
        self.treeWidget.setSortingEnabled(True)
        self.pushButton.setText(_translate("devConsole", "Plugins"))

from PyQt5.Qsci import QsciScintilla
