# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Pankaj\ABXpulse\REPO\SOURCE\SCRIPTS\PYTHON\LightNPray\lib\MayaAddon\inp_render_setting_ui.ui'
#
# Created: Mon Nov 01 19:26:27 2010
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(447, 504)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.settingsTab = QtGui.QTabWidget(Form)
        self.settingsTab.setObjectName("settingsTab")
        self.projectGlobalsTab = QtGui.QWidget()
        self.projectGlobalsTab.setObjectName("projectGlobalsTab")
        self.gridLayout_21 = QtGui.QGridLayout(self.projectGlobalsTab)
        self.gridLayout_21.setMargin(1)
        self.gridLayout_21.setHorizontalSpacing(1)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.scrollArea = QtGui.QScrollArea(self.projectGlobalsTab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 419, 425))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_24 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_24.setSpacing(2)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.groupBox_5 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayout_6 = QtGui.QFormLayout(self.groupBox_5)
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setContentsMargins(9, 9, -1, -1)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_15 = QtGui.QLabel(self.groupBox_5)
        self.label_15.setMinimumSize(QtCore.QSize(75, 0))
        self.label_15.setObjectName("label_15")
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_15)
        self.label_17 = QtGui.QLabel(self.groupBox_5)
        self.label_17.setMinimumSize(QtCore.QSize(75, 0))
        self.label_17.setObjectName("label_17")
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtGui.QLabel(self.groupBox_5)
        self.label_18.setMinimumSize(QtCore.QSize(75, 0))
        self.label_18.setObjectName("label_18")
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_18)
        self.resolutionPrjCB = QtGui.QComboBox(self.groupBox_5)
        self.resolutionPrjCB.setObjectName("resolutionPrjCB")
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.resolutionPrjCB)
        self.imageFormatCB = QtGui.QComboBox(self.groupBox_5)
        self.imageFormatCB.setObjectName("imageFormatCB")
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.imageFormatCB)
        self.imageDepthCB = QtGui.QComboBox(self.groupBox_5)
        self.imageDepthCB.setObjectName("imageDepthCB")
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.imageDepthCB)
        self.gridLayout_24.addWidget(self.groupBox_5, 2, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_4 = QtGui.QFormLayout(self.groupBox_4)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setMinimumSize(QtCore.QSize(75, 0))
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.isStereoPrjChkB = QtGui.QCheckBox(self.groupBox_4)
        self.isStereoPrjChkB.setObjectName("isStereoPrjChkB")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.isStereoPrjChkB)
        self.label_19 = QtGui.QLabel(self.groupBox_4)
        self.label_19.setMinimumSize(QtCore.QSize(75, 0))
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_19)
        self.rendererCB = QtGui.QComboBox(self.groupBox_4)
        self.rendererCB.setObjectName("rendererCB")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.rendererCB)
        self.renderEngineCB = QtGui.QComboBox(self.groupBox_4)
        self.renderEngineCB.setObjectName("renderEngineCB")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.renderEngineCB)
        self.gridLayout_24.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_6.setObjectName("groupBox_6")
        self.formLayout_5 = QtGui.QFormLayout(self.groupBox_6)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_20 = QtGui.QLabel(self.groupBox_6)
        self.label_20.setMinimumSize(QtCore.QSize(75, 0))
        self.label_20.setObjectName("label_20")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtGui.QLabel(self.groupBox_6)
        self.label_21.setMinimumSize(QtCore.QSize(75, 0))
        self.label_21.setObjectName("label_21")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_21)
        self.deviceDSB = QtGui.QDoubleSpinBox(self.groupBox_6)
        self.deviceDSB.setProperty("value", QtCore.QVariant(1.77))
        self.deviceDSB.setObjectName("deviceDSB")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.deviceDSB)
        self.pixelDSB = QtGui.QDoubleSpinBox(self.groupBox_6)
        self.pixelDSB.setProperty("value", QtCore.QVariant(1.0))
        self.pixelDSB.setObjectName("pixelDSB")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.pixelDSB)
        self.gridLayout_24.addWidget(self.groupBox_6, 3, 0, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_7.setObjectName("groupBox_7")
        self.formLayout_7 = QtGui.QFormLayout(self.groupBox_7)
        self.formLayout_7.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_9 = QtGui.QLabel(self.groupBox_7)
        self.label_9.setMinimumSize(QtCore.QSize(75, 0))
        self.label_9.setObjectName("label_9")
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.mayaVersionLE = QtGui.QLineEdit(self.groupBox_7)
        self.mayaVersionLE.setEnabled(False)
        self.mayaVersionLE.setObjectName("mayaVersionLE")
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.mayaVersionLE)
        self.gridLayout_24.addWidget(self.groupBox_7, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_24.addItem(spacerItem, 4, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_21.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.settingsTab.addTab(self.projectGlobalsTab, "")
        self.sceneSettingsTab = QtGui.QWidget()
        self.sceneSettingsTab.setObjectName("sceneSettingsTab")
        self.gridLayout_26 = QtGui.QGridLayout(self.sceneSettingsTab)
        self.gridLayout_26.setMargin(1)
        self.gridLayout_26.setHorizontalSpacing(1)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.scrollArea_2 = QtGui.QScrollArea(self.sceneSettingsTab)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget(self.scrollArea_2)
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 403, 456))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_25 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_25.setSpacing(2)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.workFileLabel = QtGui.QLabel(self.groupBox_2)
        self.workFileLabel.setMinimumSize(QtCore.QSize(75, 0))
        self.workFileLabel.setObjectName("workFileLabel")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.workFileLabel)
        self.workFileLE = QtGui.QLineEdit(self.groupBox_2)
        self.workFileLE.setEnabled(False)
        self.workFileLE.setObjectName("workFileLE")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.workFileLE)
        self.renderTypeLabel = QtGui.QLabel(self.groupBox_2)
        self.renderTypeLabel.setObjectName("renderTypeLabel")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.renderTypeLabel)
        self.renderTypeCB = QtGui.QComboBox(self.groupBox_2)
        self.renderTypeCB.setObjectName("renderTypeCB")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.renderTypeCB)
        self.renderAsLabel = QtGui.QLabel(self.groupBox_2)
        self.renderAsLabel.setObjectName("renderAsLabel")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.renderAsLabel)
        self.charBgCB = QtGui.QComboBox(self.groupBox_2)
        self.charBgCB.setObjectName("charBgCB")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.charBgCB)
        self.gridLayout_25.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_3 = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_23 = QtGui.QLabel(self.groupBox_3)
        self.label_23.setMinimumSize(QtCore.QSize(75, 0))
        self.label_23.setObjectName("label_23")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_23)
        self.cameraCB = QtGui.QComboBox(self.groupBox_3)
        self.cameraCB.setObjectName("cameraCB")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.cameraCB)
        self.isStereoChkB = QtGui.QCheckBox(self.groupBox_3)
        self.isStereoChkB.setObjectName("isStereoChkB")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.isStereoChkB)
        self.gridLayout_25.addWidget(self.groupBox_3, 7, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_25.addItem(spacerItem1, 9, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.isFrameRangeChkB = QtGui.QCheckBox(self.groupBox)
        self.isFrameRangeChkB.setObjectName("isFrameRangeChkB")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.isFrameRangeChkB)
        self.startFrameSB = QtGui.QSpinBox(self.groupBox)
        self.startFrameSB.setMaximumSize(QtCore.QSize(80, 16777215))
        self.startFrameSB.setMaximum(999999999)
        self.startFrameSB.setProperty("value", QtCore.QVariant(1001))
        self.startFrameSB.setObjectName("startFrameSB")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.startFrameSB)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.endFrameSB = QtGui.QSpinBox(self.groupBox)
        self.endFrameSB.setMaximumSize(QtCore.QSize(80, 16777215))
        self.endFrameSB.setMaximum(999999999)
        self.endFrameSB.setProperty("value", QtCore.QVariant(1101))
        self.endFrameSB.setObjectName("endFrameSB")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.endFrameSB)
        self.label_22 = QtGui.QLabel(self.groupBox)
        self.label_22.setObjectName("label_22")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_22)
        self.frameRangeLE = QtGui.QLineEdit(self.groupBox)
        self.frameRangeLE.setEnabled(False)
        self.frameRangeLE.setObjectName("frameRangeLE")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.frameRangeLE)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setMinimumSize(QtCore.QSize(75, 0))
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.gridLayout_25.addWidget(self.groupBox, 6, 0, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_8.setObjectName("groupBox_8")
        self.formLayout_8 = QtGui.QFormLayout(self.groupBox_8)
        self.formLayout_8.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_8.setContentsMargins(9, 9, -1, -1)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_24 = QtGui.QLabel(self.groupBox_8)
        self.label_24.setMinimumSize(QtCore.QSize(75, 0))
        self.label_24.setObjectName("label_24")
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_24)
        self.label_25 = QtGui.QLabel(self.groupBox_8)
        self.label_25.setMinimumSize(QtCore.QSize(75, 0))
        self.label_25.setObjectName("label_25")
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_25)
        self.sceneResCB = QtGui.QComboBox(self.groupBox_8)
        self.sceneResCB.setObjectName("sceneResCB")
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.FieldRole, self.sceneResCB)
        self.percentRenderSB = QtGui.QSpinBox(self.groupBox_8)
        self.percentRenderSB.setMinimum(10)
        self.percentRenderSB.setMaximum(100)
        self.percentRenderSB.setProperty("value", QtCore.QVariant(100))
        self.percentRenderSB.setObjectName("percentRenderSB")
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.FieldRole, self.percentRenderSB)
        self.curntRezLabel = QtGui.QLabel(self.groupBox_8)
        self.curntRezLabel.setObjectName("curntRezLabel")
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.FieldRole, self.curntRezLabel)
        self.gridLayout_25.addWidget(self.groupBox_8, 1, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_26.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.settingsTab.addTab(self.sceneSettingsTab, "")
        self.gridLayout.addWidget(self.settingsTab, 0, 0, 1, 3)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 1, 1, 1)
        self.renderButton = QtGui.QToolButton(Form)
        self.renderButton.setMinimumSize(QtCore.QSize(70, 25))
        self.renderButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.renderButton.setObjectName("renderButton")
        self.gridLayout.addWidget(self.renderButton, 1, 2, 1, 1)
        self.updateFileButton = QtGui.QToolButton(Form)
        self.updateFileButton.setMinimumSize(QtCore.QSize(70, 25))
        self.updateFileButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.updateFileButton.setObjectName("updateFileButton")
        self.gridLayout.addWidget(self.updateFileButton, 1, 0, 1, 1)

        self.retranslateUi(Form)
        self.settingsTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Render Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Form", "Image", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Form", "Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Form", "Image Format", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Form", "Image Depth", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Form", "Render", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Renderer", None, QtGui.QApplication.UnicodeUTF8))
        self.isStereoPrjChkB.setText(QtGui.QApplication.translate("Form", "Stereo Render", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Form", "Render Engine", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Form", "Aspect Ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Form", "Device", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Form", "Pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("Form", "Maya", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Version", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsTab.setTabText(self.settingsTab.indexOf(self.projectGlobalsTab), QtGui.QApplication.translate("Form", "Project Globals", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.workFileLabel.setText(QtGui.QApplication.translate("Form", "Work File", None, QtGui.QApplication.UnicodeUTF8))
        self.renderTypeLabel.setText(QtGui.QApplication.translate("Form", "Render Type", None, QtGui.QApplication.UnicodeUTF8))
        self.renderAsLabel.setText(QtGui.QApplication.translate("Form", "Render As", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Form", "Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Form", "Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.isStereoChkB.setText(QtGui.QApplication.translate("Form", "Stereo Render", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Frames", None, QtGui.QApplication.UnicodeUTF8))
        self.isFrameRangeChkB.setText(QtGui.QApplication.translate("Form", "Frame Range  (eg:- 1-10,15, 20-25)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Start Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Form", "End Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Frames", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("Form", "Image", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Form", "Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Form", "Percentage render", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsTab.setTabText(self.settingsTab.indexOf(self.sceneSettingsTab), QtGui.QApplication.translate("Form", "Scene Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.renderButton.setText(QtGui.QApplication.translate("Form", "Launch", None, QtGui.QApplication.UnicodeUTF8))
        self.updateFileButton.setText(QtGui.QApplication.translate("Form", "Update Scene File", None, QtGui.QApplication.UnicodeUTF8))

